### ISSUE TITLE
[Front-End] Create a more Event page(from Main Page), which will show up when the user clicks on more events button

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#11]
![more_hobbies_after_mainpage](https://user-images.githubusercontent.com/44449668/73688949-2867fc00-469b-11ea-96ef-24d6a6335510.png)

**Comment by mhassany** [comment]
Frontend ui (not connected to backend) is implemented in [this pull request](https://github.com/bestksl/SSW695/pull/59).
