### ISSUE TITLE
[Front-End] Create a more Event page(from Certain Hobby Page), which will show up when the user clicks on more events button 

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#12]
![more_events](https://user-images.githubusercontent.com/44449668/73689090-6a913d80-469b-11ea-98c8-c39f14111ed0.png)

**Comment by mhassany** [comment]
Frontend ui (not connected to backend) is implemented in [this pull request](https://github.com/bestksl/SSW695/pull/59).
