### ISSUE TITLE
[Back-End] Check Out Hobby feature under user setting page

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#14]
When clicks on created hobbies; then all the hobbies created will pop up, and on the top right corner, there will be a delete button, if the user clicks on that, then a window will pop up to make sure the user wants to delete that hobby, if yes, then delete, or rather, not to delete;

there will also one edit button, when clicks on it, we will go to a page same as creating that hobby page to allow the user to do the editing.

![user_profile](https://user-images.githubusercontent.com/44449668/73979034-711df000-48fb-11ea-8a60-aeb9e76b499b.png)

**Comment by mhassany** [comment]
implemented in [pull request 87](https://github.com/bestksl/SSW695/pull/87)
