### ISSUE TITLE
[Front-End] Create a more Blogs page(Enter from Certain Hobby Page), which will show up a list of events when the user clicks on more blogs button

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#20]
![blogs](https://user-images.githubusercontent.com/44449668/74211394-c2144800-4c5d-11ea-9ba6-35cd491b9c12.png)

**Comment by RobertZSun** [comment]
@SachinMCReddy  Could you please to work on this feature? Since it is related to blog this key feature

**Comment by SachinMCReddy** [comment]
@RobertZSun Yes

**Comment by mhassany** [comment]
implemented in [this pull request](https://github.com/bestksl/SSW695/pull/98) for mini blog.

**Comment by mhassany** [comment]
implemented in min-blog feature.
