### ISSUE TITLE
[Front-End] Create a hobby page

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#24]
![create_a_hobby](https://user-images.githubusercontent.com/44449668/74273835-157aaa80-4cdf-11ea-95bf-69a275094987.png)

**Comment by mhassany** [comment]
ui is implemented in this [pull request](https://github.com/bestksl/SSW695/pull/60) (not connected to backend yet).

**Comment by mhassany** [comment]
[complete] hobby can be created and edited in this [pull request](https://github.com/bestksl/SSW695/pull/91)
