### ISSUE TITLE
[Front-End] What a Blog Page should look like including comment page

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#26]
![blog_my_jogging_experience](https://user-images.githubusercontent.com/44449668/74278286-faac3400-4ce6-11ea-8e55-eb4e0251d4f8.png)

**Comment by RobertZSun** [comment]
@SachinMCReddy Could you please to help to work on this feature? Thanks!

**Comment by SachinMCReddy** [comment]
@RobertZSun Yes,  Will work on that.

**Comment by mhassany** [comment]
implemented in min-blog feature.
