### ISSUE TITLE
[Back-End] find the solution for recommending hobbies/events to users

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#35]
research about what kind and how complicated a recommendation system we need?
can we use one that is already available? (if so how can we configure it)
if not, how can we create one that serves our purpose?

**Comment by RobertZSun** [comment]
@chinmliu what time do you think you can give us the first draft of the document which describe the solution?

**Comment by chinmliu** [comment]
I think maybe I need to take about ten days. I will try my best to resolve that.

**Comment by chinmliu** [comment]
I found some articles that teach us how to write a single recommendation system. These articles describe writing the system for movies. I think they are similar with our theme. I will talk to haoxuan li to decide if we could imitate them. Also, I found a module called Librec. It is based on java. It contains a large number of recommendation algorithm and it can solve rating and ranking problems. Here is the github link: https://github.com/guoguibing/librec. I will also talk to haoxuan li about this.
