### ISSUE TITLE
apply architecture document feedbacks

### ISSUE THREAD

**Issue by mhassany** [bestksl/SSW695#46]
We have to apply this feedbacks on our architecture documents:

1. ![1](https://user-images.githubusercontent.com/44843729/75165132-ea855300-56ef-11ea-820d-ba0264e8952d.png)
1. ![2](https://user-images.githubusercontent.com/44843729/75165135-ea855300-56ef-11ea-919a-3407cb0145cb.png)
1. ![3](https://user-images.githubusercontent.com/44843729/75165139-ebb68000-56ef-11ea-9001-500b1ecf6df4.png)
1. ![4](https://user-images.githubusercontent.com/44843729/75165140-ec4f1680-56ef-11ea-9dd8-8ddd75aaa132.png)

**Comment by RobertZSun** [comment]
all right, will get that done by tonight

**Comment by mhassany** [comment]
who wants to work on which one of them?

- I will work on '5.4.2 Development View'.

**Comment by SachinMCReddy** [comment]
I will work on Physical View 5.4.3

**Comment by RobertZSun** [comment]
how about just who drew which part then that guy fix that part, I drew 5.3.1 context view then I will work on that part. @mhassany @bestksl @tanmaybhoir09 @chinmliu @

**Comment by mhassany** [comment]
@RobertZSun yes, that is a good idea. 
so only '5.4.4 Operational View' is left to pick.

**Comment by mhassany** [comment]
I finished '5.4.2 Development View'.

**Comment by RobertZSun** [comment]
![Context View](https://user-images.githubusercontent.com/44449668/75204714-a326b300-573f-11ea-8d98-cec81490491d.png)
I get the context view done

**Comment by chinmliu** [comment]
I will try to modify the Operational View

**Comment by chinmliu** [comment]
![image](https://user-images.githubusercontent.com/44855972/75214953-2dc9db00-575d-11ea-929a-ad33012c05fb.png)
I finish the Operational View
