### ISSUE TITLE
[Front-End] Create a Home Page(index.html) to have the header + footer + body parts｛including： hobby part; event part; blogs part｝

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#6]

**Comment by RobertZSun** [comment]
main page UI done
![mainpageDONE](https://user-images.githubusercontent.com/44449668/75391399-020f3800-58b8-11ea-80c0-dcb24025143e.png)

**Comment by mhassany** [comment]
ui is implemented in this [pull request](https://github.com/bestksl/SSW695/pull/60) (not connected to backend yet).

**Comment by mhassany** [comment]
implementated.
