### ISSUE TITLE
"Unsupported Media Type" when calling backend api

### ISSUE THREAD

**Issue by mhassany** [bestksl/SSW695#63]
When trying API in swagger ui i face this issue.

![WhatsApp Image 2020-03-11 at 3 25 06 PM](https://user-images.githubusercontent.com/44843729/76456152-fb4eed80-63ac-11ea-993a-add5ffd257ba.jpeg)

Is this a problem with the swagger, or backend?

Thanks

**Comment by bestksl** [comment]
![image](https://user-images.githubusercontent.com/43023538/76463659-2724a000-63ba-11ea-8c6e-9ca7e0e5d7f1.png)
1) Content-Type needs to be set to undefined.

2) The JsonObject in the body also needs to be uploaded through a file, and the value of the key is the same as the value in the @RequestPart of the API.

**Comment by bestksl** [comment]
![image](https://user-images.githubusercontent.com/43023538/76463800-736fe000-63ba-11ea-93cb-fd643023970b.png)
like this

**Comment by bestksl** [comment]
Sorry for this, as it could be a legacy code. Although it works, the experience may not be good

**Comment by mhassany** [comment]
> ![image](https://user-images.githubusercontent.com/43023538/76463800-736fe000-63ba-11ea-93cb-fd643023970b.png)
> like this

I don't think this will work. 
'hobby' field should be send as a normal json attribute, not like a file (since it is not a file). 
i suggest you fix this and review other apis.

**Comment by bestksl** [comment]
Got, it will fix that

**Comment by bestksl** [comment]
got it, I will fix that as soon as possible

**Comment by bestksl** [comment]
![image](https://user-images.githubusercontent.com/43023538/76468429-4fb09800-63c2-11ea-85ad-a89d66677341.png)
Most solutions are like this, I will try other solutions, try not to transfer json as  file, maybe I need a write a converter for this.
