### ISSUE TITLE
 "/" and "\"  bug  for different os 

### ISSUE THREAD

**Issue by bestksl** [bestksl/SSW695#64]
![image](https://user-images.githubusercontent.com/43023538/76472529-39a7d500-63cc-11ea-9cef-6f94387d044e.png)
I need help with that, Can anyone find a solution to distinguish "/" and "\\" according to the operating system. Add this feature to the file tool. For example, this directory needs to be adapted for different operating systems.

**Comment by mhassany** [comment]
In java you can use "/" for directories (java will handle the logic).

**Comment by mhassany** [comment]
i am closing this issue, please reopen it if needed.
