### ISSUE TITLE
Wordpress Login using UrL 

### ISSUE THREAD

**Issue by SachinMCReddy** [bestksl/SSW695#67]
Not able to login to WordPress on the Link 

Using the Admin credentials provided for the URL 
[http://3.226.20.89:8888/admin](URL)

![PHOTO-2020-03-18-14-30-46](https://user-images.githubusercontent.com/47071453/77103685-3080be80-69f1-11ea-8bac-21e0fdac2d7b.jpg)

**Expected behavior**
 Being able to login to WordPress using admin credentials

**Comment by mhassany** [comment]
Those credentials are for previous wordpress installation. For installing new one you have enter new credentials (choose yourself)
