### ISSUE TITLE
[Front-End] Create a blog Template to let a user post blogs

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#7]
![post_a_blog](https://user-images.githubusercontent.com/44449668/73689692-d031f980-469c-11ea-8b16-bd37b02a8308.png)

**Comment by RobertZSun** [comment]
@SachinMCReddy  Would you please to help me build this so that we can have user to post blogs?

**Comment by SachinMCReddy** [comment]
@RobertZSun  Definitely

**Comment by mhassany** [comment]
implemented in min-blog feature.
