### ISSUE TITLE
[Back-End] Find a solution for SSO in back-end and could be used for WordPress integration

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#71]

**Comment by mhassany** [comment]
@SachinMCReddy respond to this issue, and reference any document or link here.

**Comment by SachinMCReddy** [comment]
I have created a new issue where it mentions the alternative for the SSO solution that we discussed on Sunday, could you please check and verify if that can be a possible for SSO implementation. 

Thanks

**Comment by mhassany** [comment]
since we decided to use the mini-blog as the solution for blog feature, sso is no longer needed.
