### ISSUE TITLE
[Recommended system] document the environment and function for the events recommendation system

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#72]
the file will be like a google doc in the document folder

**Comment by chinmliu** [comment]
I have put the files in my branch. But I wonder if we need to take the location into consideration. This will imporve the accuracy of the recommend results. But it will surely make the system more complex.

**Comment by RobertZSun** [comment]
So far what you can achieve, if you can do it right now, then we are good to have it, but if not, that's totally fine without that requirement.
