### ISSUE TITLE
Please don't run docker repeatedly for no reasons, please avoid it, thanks.

### ISSUE THREAD

**Issue by bestksl** [bestksl/SSW695#76]
Please do not run docker repeatedly without any purpose, please avoid doing so, thanks!
![image](https://user-images.githubusercontent.com/43023538/77505111-9e394a00-6e38-11ea-95b9-413210c6013d.png)
And I need to fix it.

**Comment by bestksl** [comment]
![image](https://user-images.githubusercontent.com/43023538/77506191-962ed980-6e3b-11ea-96ee-55f5e99f12e9.png)
This is the record, please be aware that don't forget your username and password again, because I need  to reset the database.

**Comment by mhassany** [comment]
@bestksl I have not run (or re-run) the docker. I don't know if @SachinMCReddy (or others) have done it or not. Is there a chance if this is happening by its own or by other tools?
