### ISSUE TITLE
wordpress server doesnʻt work and lost some web pages

### ISSUE THREAD

**Issue by bestksl** [bestksl/SSW695#77]

**Comment by bestksl** [comment]
![image](https://user-images.githubusercontent.com/43023538/77507760-6aadee00-6e3f-11ea-837d-84ee8b09d009.png)
already fixed

**Comment by bestksl** [comment]
The account is 
username: admin
password: 123456
[http://3.226.20.89:8888/wp-admin/](http://3.226.20.89:8888/wp-admin/)

**Comment by bestksl** [comment]
@mhassany @SachinMCReddy Please check this and close this issue, thanks.

**Comment by mhassany** [comment]
@bestksl using provided credentials I can't access admin panel.
After login, it redirects to the same page (login).
Please check.
