### ISSUE TITLE
No add new plugin option in the wordpress admin page.

### ISSUE THREAD

**Issue by bestksl** [bestksl/SSW695#80]
![image](https://user-images.githubusercontent.com/43023538/77577245-cebacb80-6eac-11ea-86a3-81e73ffafa24.png)
I need to install an SSO plugin.
But there is no option for this.
That is strange. 
Maybe our WordPress is not the full version?

**Comment by bestksl** [comment]
@mhassany Is there any idea for this bug? thanks!

**Comment by mhassany** [comment]
there may be a problem with the wordpress or the account you used to login.
as described [here](https://www.wpbeginner.com/beginners-guide/step-by-step-guide-to-install-a-wordpress-plugin-for-beginners/), there should be an option in the side menu for installing new plugins.

first double check your username, then your wordpress user management section.
