### ISSUE TITLE
[Back-end]Youth Control Setting(Do age calculation)

### ISSUE THREAD

**Issue by RobertZSun** [bestksl/SSW695#9]
In the user setting page, we have an age calculation feature. If the age of the user is below 18, then all the activities which have age requirement(Over 18) will not represent to the user, even the user has already joined, those activities will be unjoined automatically,

and for hobbies, those hobbies which have age requirement will not be seen by those youth customers, even if they try to search a certain hobby and a certain event, and all the blogs under those hobbies will not be seen by those youth users either.

The default mode is the adult mode, once the date of birth is inputted, then do the calculation, whether this user is an adult.

![user_profile](https://user-images.githubusercontent.com/44449668/73979034-711df000-48fb-11ea-8a60-aeb9e76b499b.png)

**Comment by mhassany** [comment]
implemented in this [pull request](https://github.com/bestksl/SSW695/pull/87)
