### ISSUE TITLE
SSO possible solution 

### ISSUE THREAD

**Issue by SachinMCReddy** [bestksl/SSW695#93]
The single sign-on alternative to the one all which was previously mentioned in the meeting on Sunday ( one all SSO) 

**Additional context**
The setup we need to perform is mentioned here in the link below 
https://auth0.com/docs/cms/wordpress/installation#option-1-standard-setup

**Comment by bestksl** [comment]
So, who is responsible for the blog? There are still many days, and you have found the documentation, so go ahead and do it.

**Comment by bestksl** [comment]
@SachinMCReddy

**Comment by mhassany** [comment]
since we decided to use the mini-blog as the solution for blog feature, sso is no longer needed.
